# 应用名称
spring:
  application:
    name: coder-backend
  mail:
    host: smtp.163.com
    port: 25
    username: www_ideaworks_club@163.com
    password:
    default-encoding: UTF-8
    properties.mail.smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory
# 应用服务 WEB 访问端口
server:
  port: 8888

# 配置 smtp 服务器地址



#spring.rabbitmq.host=192.168.22.128
#spring.rabbitmq.port= 5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=test

springdoc:
  swagger-ui:
    path: /swagger
    enabled: true
  api-docs:
    enabled: true
  paths-to-match: /api/**

project:
  path: D:/code

#spring:
#  datasource:
#    druid:
#      driver-class-name: net.sourceforge.jtds.jdbc.Driver
#      username: escloud
#      password: fpSPcx5kfoNl+aZalQQcaJq0WQ3OkikNzYjBpUquEQEpCEg6AxJZWZMyts1YPIn97PYD3843FQh8j/7xdSE7Eg==
#      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIxnQJmAfL8vCTtuKViDH5FVEPC5Ao1gNOsBHgv+e6ccWV5CLJoAy1+pZPW5RWGCFYikTg6Q11oCUuC6kJAW0GcCAwEAAQ==
#      validation-query: select count(*) from S_COURT
#      validation-query-timeout: 0
#      keep-alive: true
#      time-between-log-stats-millis: 300000
#      filter:
#        config:
#          enabled: true
#        slf4j:
#          enabled: true
#        stat:
#          enabled: true
#          log-slow-sql: true
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      stat-view-servlet:
#        enabled: true
#        allow: '*'
#        url-pattern: /druid/*
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SybaseDialect
#        default_schema: escloud
#    show-sql: false
#  transaction:
#    aop:
#      required-methods: insert*,add*,save*,update*,delete*,remove*
#
#system:
#  esshare-db:
#    driver-class-name: net.sourceforge.jtds.jdbc.Driver
#    url: jdbc:jtds:sybase://142.2.248.206:8888/esshare6;charset=cp936
#    user: esshare6
#    password: eastsoft.cn
